# Generated by Django 5.1 on 2025-12-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_delivery_item"),
        ("transactions", "0003_alter_sale_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="transactions.sale",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
