# Generated by Django 5.1 on 2025-12-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_remove_invoice_delivery"),
        ("store", "0003_delivery_date_created_delivery_sale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="invoice.invoice",
            ),
        ),
    ]
