# Generated by Django 5.1 on 2025-12-10 09:43

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='purchase', unique=True)),
                ('payment_details', models.CharField(help_text='Details of the payment', max_length=255)),
                ('status', models.BooleanField(default=False, help_text='Payment status of the bill', verbose_name='Paid')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.purchase')),
            ],
        ),
    ]
