# Generated by Django 5.1 on 2025-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="status",
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("AD", "Admin"), ("MA", "Manager"), ("ST", "Staff")],
                default="ST",
                max_length=12,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
