# Generated by Django 5.1 on 2025-12-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_status_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Staff", "Staff"),
                ],
                default="ST",
                max_length=12,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
