# Generated by Django 5.1 on 2025-12-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("transactions", "0002_alter_purchase_slug_alter_purchase_total_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                db_column="customer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.customer",
            ),
        ),
    ]
