# Generated by Django 5.1 on 2025-12-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("transactions", "0003_alter_sale_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="accounts.vendor",
            ),
        ),
    ]
