# Generated by Django 5.1 on 2025-12-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_remove_invoice_contact_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="delivery",
        ),
    ]
